name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: |
          docker build -t lasithdev/civilink-user-management-server:${{github.sha}} .
          docker tag lasithdev/civilink-user-management-server:${{github.sha}} lasithdev/civilink-user-management-server:latest

      - name: Push Docker Image to Docker hub
        run: |
          docker push lasithdev/civilink-user-management-server:latest

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud components update

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials civilink-cluster --zone us-central1-c --project ${{ secrets.GCP_PROJECT }}

      - name: Update GKE Deployment
        run: |
          kubectl set image deployment/civilink-user-management civilink-user-management=lasithdev/civilink-user-management-server:latest:latest -n development
          kubectl rollout restart deployment civilink-user-management -n development